import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import Head from 'next/head';
import Image from 'next/image';
import { useTranslation } from 'react-i18next';

import LangageSelector from '../components/Langage-selector';
import styles from '../styles/Home.module.css';

export default function Home(props) {

  const { t, i18n } = useTranslation();


  return (
    <div className={styles.container}>
      
      <LangageSelector />
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          {t('common:coco')}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
        
      </footer>
    </div>
  )
}

export async function getStaticProps({ locale }){
  return {
    props: {
      ...await serverSideTranslations(locale, ['common']),
    },
  };
}
